// Generated by release.sh — do not edit by hand.

export interface ReleaseInfo {
  version: string;
  versionCode: number;
  releasedAt: string;
}

export const releaseInfo: ReleaseInfo = {
  version: '0.3.0',
  versionCode: 8,
  releasedAt: '2026-09-17T07:21:17.058Z',
};
