// Generated by release.sh — do not edit by hand.

export interface ReleaseInfo {
  version: string;
  versionCode: number;
  releasedAt: string;
}

export const releaseInfo: ReleaseInfo = {
  version: '1.0.0',
  versionCode: 10,
  releasedAt: '2026-09-20T10:46:06.115Z',
};
