// Generated by release.sh — do not edit by hand.

export interface ReleaseInfo {
  version: string;
  versionCode: number;
  releasedAt: string;
}

export const releaseInfo: ReleaseInfo = {
  version: '0.1.1',
  versionCode: 2,
  releasedAt: '2026-09-16T09:16:48.186Z',
};
