const fs = require('fs');
const path = require('path');

const version = process.argv[2];
if (!version) {
  console.error('usage: node scripts/update-version.js <version>');
  process.exit(1);
}

const root = path.join(__dirname, '..');
const appJsonPath = path.join(root, 'app.json');
const raw = JSON.parse(fs.readFileSync(appJsonPath, 'utf8'));
const expo = raw.expo || raw;
const versionCode = (expo.android && expo.android.versionCode ? expo.android.versionCode : 0) + 1;

expo.version = version;
expo.android = expo.android || {};
expo.android.versionCode = versionCode;

fs.writeFileSync(appJsonPath, JSON.stringify(raw, null, 2) + '\n');

const releasedAt = new Date().toISOString();
const releaseInfoPath = path.join(root, 'src', 'config', 'release-info.ts');
const releaseInfoContent = [
  '// Generated by release.sh \u2014 do not edit by hand.',
  '',
  'export interface ReleaseInfo {',
  '  version: string;',
  '  versionCode: number;',
  '  releasedAt: string;',
  '}',
  '',
  'export const releaseInfo: ReleaseInfo = {',
  `  version: '${version}',`,
  `  versionCode: ${versionCode},`,
  `  releasedAt: '${releasedAt}',`,
  '};',
  '',
].join('\n');
fs.writeFileSync(releaseInfoPath, releaseInfoContent);

process.stdout.write(String(versionCode));